### ISSUE TITLE
Librewolf closes after 1 or 2 min approx on win7x64

### ISSUE THREAD

**Issue by tutak-kat** [adeii/supermium-portable#4]
Hi,
I saw your discussion here:
https://github.com/Eclipse-Community/r3dfox/issues/39
you had the same problem with Librewolf that it closes after 90s.
How did you resolved the problem?
Thanks

**Comment by adeii** [comment]
I guess that problem is in the line 535 in firefox.js, inside omni.ja package.
Thanks to @K4sum1, fixed line is:   pref("browser.taskbar.lists.legacyBackend", true);
You could try on the latest version:
https://github.com/adeii/supermium-portable/releases/download/F1235/librewolf-125.0.2-1-win7-x64-portable.7z
https://github.com/adeii/supermium-portable/releases/download/F1235/librewolf-125.0.2-1-win7-x86-portable.7z

**Comment by tutak-kat** [comment]
Thanks Adeii for your answer.
I saw that he said that it is not possible to edit that line in about:config since it will close firefox anyway.
So would you mind to give a little bit more information regarding changing that pref - where I can find it, what file I need to edit.
You said it is 535 line in firefox.js inside omni.ja package - how I can edit omni.ja file?
That omni.js is a big file I suposed I can't just use r3dfox omni.js file? I tried but librewolf still closing.
Then there is a 2 omni.js file one in root folder and another in browser folder.
Also I need to replace 3 files from r3dfox:
lgpllibs.dll
mozglue.dll
xul.dll?
Thanks

**Comment by tutak-kat** [comment]
Resolved the problem.
In my case line was 524.
Thanks

**Comment by adeii** [comment]
omni.ja is ZIP archive, inside _browser_ folder. Just that one line need to be changed, but need for r3dfox's omni.ja.
And those 3 DLL files.
